Repository USKhokhar/fehrist, pull requests merged in 2023-10, with the labels that each got.

#2 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, enhancement, hacktoberfest

#3 Updated CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, enhancement, hacktoberfest

#6 train_to_pakistan
  src/content/posts/train-to-pakistan.md
Labels: hacktoberfest

#7 looking_for_alaska
  src/content/posts/looking-for-alaska.md
Labels: hacktoberfest

#10 added contributors section to README.md
  README.md
Labels: documentation, enhancement, hacktoberfest

#12 Added Summary
  src/content/posts/after-we-collided.md
Labels: hacktoberfest

#16 Utkarsh : The Mayor Of Casterbridge
  src/content/posts/the-mayor-of-casterbridge.md
Labels: hacktoberfest

#39 Tanishka: Inside Chanakya's Mind
  src/content/posts/inside-chanakya's-mind
Labels: documentation, enhancement, hacktoberfest

#43 Tanishka:Ugly Love
  src/content/posts/ugly-love.md
Labels: documentation, good first issue, hacktoberfest

#51 Tanishka: The 48 Laws of Power
  src/content/posts/the-48-laws-of-power.md
Labels: hacktoberfest

#52 Tanishka: The Art of Manipulation: How to Get Anybody to Do What You Want
  src/content/posts/the-art-of-manipulation.md
Labels: hacktoberfest

#60 Mohit: the interpretation of dreams
  src/content/posts/the-interpretation-of-dreams.md
Labels: hacktoberfest

#61 Create Think-and-Grow-Rich.md
  src/content/posts/Think-and-Grow-Rich.md
Labels: hacktoberfest

#69 Vikas: The Hidden Hindu
  src/content/posts/the-hidden-hindu.md
Labels: hacktoberfest

#70 Footer made to always stick to bottom
  src/pages/index.astro
Labels: bug, enhancement, hacktoberfest, hacktoberfest-accepted

#72 Mohit bhart:The Children Of God: The inside story
  src/content/posts/the-children-of-god-the-inside-story.md
Labels: hacktoberfest, hacktoberfest-accepted
